### ISSUE TITLE
   Config populated with vfs objects = vfs objects = acl_xattr

### ISSUE THREAD

**Issue by mechanysm** [dlandon/active.directory#1]
Hi there, 

This section of code seems to be causing the the smb-shares.conf to be populated with  "vfs objects = vfs objects = acl_xattr" rather than "vfs objects = acl_xattr" happens on every reboot or stop/start of the unraid array.

Are you able to adjust this to prevent this from happening as it seems to be causing shares to become inaccessible in my case until I remove this setting.

foreach ($smb_shares as $s) {
		if ($s != "global") {
			if (isset($smb_config[$s]['vfs objects'])) {
				/* Remove all occurrences of $acl_xattr from the vfs objects string */
				$smb_config[$s]['vfs objects'] = str_replace($acl_xattr, '', $smb_config[$s]['vfs objects']);

				/* Trim the result to clean up any extra spaces left after removal */
				$smb_config[$s]['vfs objects'] = trim($smb_config[$s]['vfs objects']);

				/* Add the acl_xattr. */
				$smb_config[$s]['vfs objects'] .= " ".$acl_xattr;
			} else {
				/* Add the vfs objects = acl_xattr. */
				$smb_config[$s]['vfs objects'] = "vfs objects = ".$acl_xattr;
			}
		}
	}

**Comment by dlandon** [comment]
Post diagnostics.  I don't see how that can happen.

**Comment by dlandon** [comment]
I found it.  Fixed in the next release.
